In [113]:

import rtree, pygeos
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import os
import folium

import numpy as np
from matplotlib import pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
import statsmodels.api as sm
from datetime import datetime, timedelta

In [259]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [260]:

data_path = 'C:/Users/mhudgell/data/dsa-jake/'
os.listdir(data_path)

['1 Team & Station Trip Level Data - April 2024 - Randomised.csv',
 'Total Number of Vehicles in Fleet - April 2024.csv',
 'Workshop Data - April 2024 - Randomised.csv']

In [261]:
file_path = data_path +'1 Team & Station Trip Level Data - April 2024 - Randomised.csv'
trip = pd.read_csv(file_path)

In [262]:
real_trip = trip[(trip['Hours'] >= 0.0)] #0.4
real_trip['label'] = "Unavailable"

In [263]:
real_trip.head(10)

,Registration,Fleet,Vehicle Function,Station,Date,Time - Start,Time - End,Trip Count,Miles Travelled,Hours,Speed,label
0,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,00:36:19,01:16:04,1,2.49,0.66,3.77,Unavailable
1,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,02:23:22,02:30:37,1,2.30,0.12,19.17,Unavailable
2,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:24:11,03:32:05,1,2.24,0.13,17.23,Unavailable
3,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:48:21,03:54:24,1,1.93,0.10,19.30,Unavailable
4,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:59:36,05:46:48,1,37.97,1.79,21.21,Unavailable
5,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,10:02:54,10:12:15,1,2.11,0.16,13.19,Unavailable
6,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,10:27:19,10:52:46,1,8.14,0.42,19.38,Unavailable
7,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,11:12:26,11:17:59,1,1.43,0.09,15.89,Unavailable
8,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,11:33:57,11:53:06,1,5.66,0.32,17.69,Unavailable
9,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,12:30:13,12:32:25,1,0.68,0.04,17.00,Unavailable

In [264]:

sorted_df = real_trip.sort_values(by=['Date', 'Registration'], ascending=True)

In [265]:
sorted_df['unavail_start']  = pd.to_datetime(sorted_df['Date'] + ' ' + sorted_df['Time - Start'])
sorted_df['unavail_end']  = pd.to_datetime(sorted_df['Date'] + ' ' + sorted_df['Time - End'])

sorted_df.tail()

,Registration,Fleet,Vehicle Function,Station,Date,Time - Start,Time - End,Trip Count,Miles Travelled,Hours,Speed,label,unavail_start,unavail_end
5103,FFFFFF,South Worcestershire,PATROL,WORCESTER,30-Apr-24,13:22:19,13:32:22,1,2.49,0.17,14.65,Unavailable,2024-04-30 13:22:19,2024-04-30 13:32:22
5104,FFFFFF,South Worcestershire,PATROL,WORCESTER,30-Apr-24,13:34:41,13:40:02,1,0.62,0.09,6.89,Unavailable,2024-04-30 13:34:41,2024-04-30 13:40:02
5105,FFFFFF,South Worcestershire,PATROL,WORCESTER,30-Apr-24,14:45:16,15:08:49,1,4.97,0.39,12.74,Unavailable,2024-04-30 14:45:16,2024-04-30 15:08:49
5106,FFFFFF,South Worcestershire,PATROL,WORCESTER,30-Apr-24,22:33:29,23:02:11,1,13.05,0.48,27.19,Unavailable,2024-04-30 22:33:29,2024-04-30 23:02:11
5107,FFFFFF,South Worcestershire,PATROL,WORCESTER,30-Apr-24,23:06:24,23:42:36,1,9.32,0.60,15.53,Unavailable,2024-04-30 23:06:24,2024-04-30 23:42:36

In [266]:
len(sorted_df.index)

5108

In [267]:

midnight_df = sorted_df[(sorted_df['unavail_end'] < sorted_df['unavail_start'])]

sorted_df['new_row'] = False
new_row_list = []
new_endtime = '23:59:59'
for idx, row in sorted_df.iterrows():
    if sorted_df.at[idx,'unavail_end'] < sorted_df.at[idx,'unavail_start']:
        new_row_copy = row.copy(deep=True)
        new_row_list.append(new_row_copy)
        sorted_df.at[idx, 'Time - End'] = new_endtime

In [268]:
print(len(new_row_list))
print(len(midnight_df.index))

70
70

In [269]:
new_df = pd.DataFrame(new_row_list)

In [270]:
new_df['Time - Start'] = '00:00:01'
new_df['new_row'] = True

In [271]:
new_df['Date'] = pd.to_datetime(new_df['Date']) + timedelta(days=1)
new_df['Date'] = new_df['Date'].dt.strftime('%Y-%m-%d')

In [272]:
new_df['Time - End'] = new_df['unavail_end'].dt.time

new_df['Time - End'] = new_df['Time - End'].astype(str)

In [273]:
new_df['unavail_start']  = pd.to_datetime(new_df['Date'] + ' ' + new_df['Time - Start']) 
new_df['unavail_end']  = pd.to_datetime(new_df['Date'] + ' ' + new_df['Time - End'])

In [274]:
sorted_df = sorted_df.append(new_df)
sorted_df['homeStationStart'] = True
sorted_df['homeStationEnd'] = True

In [275]:
sorted_df

,Registration,Fleet,Vehicle Function,Station,Date,Time - Start,Time - End,Trip Count,Miles Travelled,Hours,Speed,label,unavail_start,unavail_end,new_row,homeStationStart,homeStationEnd
0,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,00:36:19,01:16:04,1,2.49,0.66,3.77,Unavailable,2024-04-01 00:36:19,2024-04-01 01:16:04,False,True,True
1,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,02:23:22,02:30:37,1,2.30,0.12,19.17,Unavailable,2024-04-01 02:23:22,2024-04-01 02:30:37,False,True,True
2,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:24:11,03:32:05,1,2.24,0.13,17.23,Unavailable,2024-04-01 03:24:11,2024-04-01 03:32:05,False,True,True
3,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:48:21,03:54:24,1,1.93,0.10,19.30,Unavailable,2024-04-01 03:48:21,2024-04-01 03:54:24,False,True,True
4,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:59:36,05:46:48,1,37.97,1.79,21.21,Unavailable,2024-04-01 03:59:36,2024-04-01 05:46:48,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2801,AAAAAA,South Worcestershire,PATROL,WORCESTER,2024-04-28,00:00:01,00:18:42,1,3.92,0.38,10.32,Unavailable,2024-04-28 00:00:01,2024-04-28 00:18:42,True,True,True
5088,FFFFFF,South Worcestershire,PATROL,WORCESTER,2024-04-28,00:00:01,00:20:51,1,15.54,0.86,18.07,Unavailable,2024-04-28 00:00:01,2024-04-28 00:20:51,True,True,True
1104,444444,South Worcestershire,PATROL,WORCESTER,2024-04-29,00:00:01,00:26:56,1,14.29,0.48,29.77,Unavailable,2024-04-29 00:00:01,2024-04-29 00:26:56,True,True,True
1818,666666,South Worcestershire,PATROL,WORCESTER,2024-04-29,00:00:01,00:00:37,1,1.24,0.13,9.54,Unavailable,2024-04-29 00:00:01,2024-04-29 00:00:37,True,True,True
3402,BBBBBB,South Worcestershire,PATROL,WORCESTER,2024-04-30,00:00:01,00:49:00,1,22.19,0.90,24.66,Unavailable,2024-04-30 00:00:01,2024-04-30 00:49:00,True,True,True

In [276]:
file_path = data_path +'1 Team & Station Trip Level Data - April 2024 - Randomised Updated.csv'
sorted_df.to_csv(file_path)