In [1]:

import rtree, pygeos
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import os
import folium

import numpy as np
from matplotlib import pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
import statsmodels.api as sm

C:\Anaconda3\envs\geo37\lib\site-packages\geopandas\_compat.py:110: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.10.3-CAPI-1.16.1). Conversions between both will be slow.
  shapely_geos_version, geos_capi_version_string

In [2]:
%%javascript
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [113]:

data_path = 'C:/Users/mhudgell/data/dsa-jake/'
os.listdir(data_path)

['1 Team & Station Trip Level Data - April 2024 - Randomised.csv',
 'Total Number of Vehicles in Fleet - April 2024.csv',
 'Workshop Data - April 2024 - Randomised.csv']

In [114]:
file_path = data_path +'1 Team & Station Trip Level Data - April 2024 - Randomised.csv'
trip = pd.read_csv(file_path)

In [130]:
real_trip = trip[(trip['Hours'] >= 0.0)] #0.4
real_trip['label'] = "Unavailable"

In [131]:
real_trip.head(10)

,Registration,Fleet,Vehicle Function,Station,Date,Time - Start,Time - End,Trip Count,Miles Travelled,Hours,Speed,label
0,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,00:36:19,01:16:04,1,2.49,0.66,3.77,Unavailable
1,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,02:23:22,02:30:37,1,2.30,0.12,19.17,Unavailable
2,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:24:11,03:32:05,1,2.24,0.13,17.23,Unavailable
3,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:48:21,03:54:24,1,1.93,0.10,19.30,Unavailable
4,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:59:36,05:46:48,1,37.97,1.79,21.21,Unavailable
5,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,10:02:54,10:12:15,1,2.11,0.16,13.19,Unavailable
6,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,10:27:19,10:52:46,1,8.14,0.42,19.38,Unavailable
7,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,11:12:26,11:17:59,1,1.43,0.09,15.89,Unavailable
8,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,11:33:57,11:53:06,1,5.66,0.32,17.69,Unavailable
9,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,12:30:13,12:32:25,1,0.68,0.04,17.00,Unavailable

In [132]:
# to process all data we need to worry about:
#
# Fleet Vehicle Function Station
# also if car does no journies then availability will not come up need master list of available vehicles.
#
current_reg = ""
current_date = '01-Jan-70'
sorted_df = real_trip.sort_values(by=['Date', 'Registration'], ascending=True)

In [133]:
sorted_df = sorted_df[(sorted_df['Date'] >= '01-Apr-24')]

sorted_df['unavail_start']  = pd.to_datetime(sorted_df['Date'] + ' ' + sorted_df['Time - Start'])
sorted_df['unavail_end']  = pd.to_datetime(sorted_df['Date'] + ' ' + sorted_df['Time - End'])

sorted_df.head()

,Registration,Fleet,Vehicle Function,Station,Date,Time - Start,Time - End,Trip Count,Miles Travelled,Hours,Speed,label,unavail_start,unavail_end
0,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,00:36:19,01:16:04,1,2.49,0.66,3.77,Unavailable,2024-04-01 00:36:19,2024-04-01 01:16:04
1,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,02:23:22,02:30:37,1,2.30,0.12,19.17,Unavailable,2024-04-01 02:23:22,2024-04-01 02:30:37
2,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:24:11,03:32:05,1,2.24,0.13,17.23,Unavailable,2024-04-01 03:24:11,2024-04-01 03:32:05
3,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:48:21,03:54:24,1,1.93,0.10,19.30,Unavailable,2024-04-01 03:48:21,2024-04-01 03:54:24
4,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:59:36,05:46:48,1,37.97,1.79,21.21,Unavailable,2024-04-01 03:59:36,2024-04-01 05:46:48

In [134]:
#query_start = '01-Apr-24 3:30'
#query_end = '01-Apr-24 04:00'

# still need to work out what to do with the wrap around trips i.e. over teh day

#temp_df = sorted_df  #sorted_df[(sorted_df['unavail_start'] < sorted_df['unavail_end'])]

#over_df  = temp_df[((temp_df['unavail_start'] > query_start ) & (temp_df['unavail_start'] <= query_end))]
#start_df  = temp_df[((temp_df['unavail_start'] >= query_start ) & (temp_df['unavail_start'] <= query_end))]
#end_df = temp_df[((temp_df['unavail_end'] >= query_start ) & (temp_df['unavail_end'] <= query_end))]

In [135]:
start_df

,Registration,Fleet,Vehicle Function,Station,Date,Time - Start,Time - End,Trip Count,Miles Travelled,Hours,Speed,label,unavail_start,unavail_end
3,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:48:21,03:54:24,1,1.93,0.10,19.30,Unavailable,2024-04-01 03:48:21,2024-04-01 03:54:24
4,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:59:36,05:46:48,1,37.97,1.79,21.21,Unavailable,2024-04-01 03:59:36,2024-04-01 05:46:48
2175,999999,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:51:22,04:15:55,1,9.88,0.41,24.10,Unavailable,2024-04-01 03:51:22,2024-04-01 04:15:55
2567,AAAAAA,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:50:36,03:52:15,1,0.62,0.03,20.67,Unavailable,2024-04-01 03:50:36,2024-04-01 03:52:15

In [136]:
end_df

,Registration,Fleet,Vehicle Function,Station,Date,Time - Start,Time - End,Trip Count,Miles Travelled,Hours,Speed,label,unavail_start,unavail_end
2,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:24:11,03:32:05,1,2.24,0.13,17.23,Unavailable,2024-04-01 03:24:11,2024-04-01 03:32:05
3,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:48:21,03:54:24,1,1.93,0.10,19.30,Unavailable,2024-04-01 03:48:21,2024-04-01 03:54:24
2174,999999,South Worcestershire,PATROL,WORCESTER,01-Apr-24,02:54:45,03:51:00,1,24.61,0.94,26.18,Unavailable,2024-04-01 02:54:45,2024-04-01 03:51:00
2566,AAAAAA,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:25:53,03:31:29,1,1.99,0.09,22.11,Unavailable,2024-04-01 03:25:53,2024-04-01 03:31:29
2567,AAAAAA,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:50:36,03:52:15,1,0.62,0.03,20.67,Unavailable,2024-04-01 03:50:36,2024-04-01 03:52:15
3943,DDDDDD,South Worcestershire,PATROL,WORCESTER,01-Apr-24,02:21:34,03:50:01,1,16.16,1.47,10.99,Unavailable,2024-04-01 02:21:34,2024-04-01 03:50:01

In [137]:
over_df

,Registration,Fleet,Vehicle Function,Station,Date,Time - Start,Time - End,Trip Count,Miles Travelled,Hours,Speed,label,unavail_start,unavail_end
3,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:48:21,03:54:24,1,1.93,0.10,19.30,Unavailable,2024-04-01 03:48:21,2024-04-01 03:54:24
4,111111,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:59:36,05:46:48,1,37.97,1.79,21.21,Unavailable,2024-04-01 03:59:36,2024-04-01 05:46:48
2175,999999,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:51:22,04:15:55,1,9.88,0.41,24.10,Unavailable,2024-04-01 03:51:22,2024-04-01 04:15:55
2567,AAAAAA,South Worcestershire,PATROL,WORCESTER,01-Apr-24,03:50:36,03:52:15,1,0.62,0.03,20.67,Unavailable,2024-04-01 03:50:36,2024-04-01 03:52:15

In [139]:
from datetime import datetime, timedelta
num_veh = 5
avail_list = []
avail_time = []
query_start = pd.to_datetime('01-Apr-24 00:00')
for loop in range(0,48):

    if loop == 47:
        query_end = query_start + timedelta(minutes=29)
    else:
        query_end = query_start + timedelta(minutes=30)


    
    sorted_df = sorted_df[(sorted_df['unavail_start'] < sorted_df['unavail_end'])] # need to fix removes day overlaps
    
    temp_df = sorted_df[((sorted_df['unavail_start'] <= query_start ) & (sorted_df['unavail_start'] >= query_end)) | # over
                        ((sorted_df['unavail_start'] > query_start ) & (sorted_df['unavail_start'] <= query_end)) | # starts
                        ((sorted_df['unavail_end'] >= query_start ) & (sorted_df['unavail_end'] <= query_end))]      # ends
    
    print(query_start, query_end, len(temp_df.index), len(temp_df.groupby(['Registration'])))
    avail_time.append(query_start)
    avail_list.append(num_veh  -len(temp_df.groupby(['Registration'])))
    query_start = query_end

2024-04-01 00:00:00 2024-04-01 00:30:00 3 3
2024-04-01 00:30:00 2024-04-01 01:00:00 6 4
2024-04-01 01:00:00 2024-04-01 01:30:00 4 3
2024-04-01 01:30:00 2024-04-01 02:00:00 7 5
2024-04-01 02:00:00 2024-04-01 02:30:00 6 5
2024-04-01 02:30:00 2024-04-01 03:00:00 6 5
2024-04-01 03:00:00 2024-04-01 03:30:00 9 4
2024-04-01 03:30:00 2024-04-01 04:00:00 8 4
2024-04-01 04:00:00 2024-04-01 04:30:00 3 3
2024-04-01 04:30:00 2024-04-01 05:00:00 3 2
2024-04-01 05:00:00 2024-04-01 05:30:00 4 3
2024-04-01 05:30:00 2024-04-01 06:00:00 3 3
2024-04-01 06:00:00 2024-04-01 06:30:00 0 0
2024-04-01 06:30:00 2024-04-01 07:00:00 1 1
2024-04-01 07:00:00 2024-04-01 07:30:00 0 0
2024-04-01 07:30:00 2024-04-01 08:00:00 2 1
2024-04-01 08:00:00 2024-04-01 08:30:00 3 3
2024-04-01 08:30:00 2024-04-01 09:00:00 5 3
2024-04-01 09:00:00 2024-04-01 09:30:00 2 2
2024-04-01 09:30:00 2024-04-01 10:00:00 1 1
2024-04-01 10:00:00 2024-04-01 10:30:00 4 3
2024-04-01 10:30:00 2024-04-01 11:00:00 3 2
2024-04-01 11:00:00 2024-04-01 11:30:00 3 3
2024-04-01 11:30:00 2024-04-01 12:00:00 4 3
2024-04-01 12:00:00 2024-04-01 12:30:00 0 0
2024-04-01 12:30:00 2024-04-01 13:00:00 2 2
2024-04-01 13:00:00 2024-04-01 13:30:00 0 0
2024-04-01 13:30:00 2024-04-01 14:00:00 2 2
2024-04-01 14:00:00 2024-04-01 14:30:00 2 2
2024-04-01 14:30:00 2024-04-01 15:00:00 1 1
2024-04-01 15:00:00 2024-04-01 15:30:00 1 1
2024-04-01 15:30:00 2024-04-01 16:00:00 1 1
2024-04-01 16:00:00 2024-04-01 16:30:00 3 3
2024-04-01 16:30:00 2024-04-01 17:00:00 5 4
2024-04-01 17:00:00 2024-04-01 17:30:00 7 5
2024-04-01 17:30:00 2024-04-01 18:00:00 6 4
2024-04-01 18:00:00 2024-04-01 18:30:00 4 3
2024-04-01 18:30:00 2024-04-01 19:00:00 7 4
2024-04-01 19:00:00 2024-04-01 19:30:00 7 4
2024-04-01 19:30:00 2024-04-01 20:00:00 6 4
2024-04-01 20:00:00 2024-04-01 20:30:00 4 3
2024-04-01 20:30:00 2024-04-01 21:00:00 6 4
2024-04-01 21:00:00 2024-04-01 21:30:00 5 5
2024-04-01 21:30:00 2024-04-01 22:00:00 3 3
2024-04-01 22:00:00 2024-04-01 22:30:00 0 0
2024-04-01 22:30:00 2024-04-01 23:00:00 2 2
2024-04-01 23:00:00 2024-04-01 23:30:00 1 1
2024-04-01 23:30:00 2024-04-01 23:59:00 1 1